apiVersion: "v1"
kind: Pod
metadata:
  name: nginx
  namespace: namespace-psp
  labels:
    name: nginx
    owner: Praparn_L
    version: "1.0"
    module: WebServer
    environment: development
spec:
  containers:
    - name: web
      image: labdocker/nginxbitnami:latest
      resources:
        requests:
          memory: "16Mi"
          cpu: "100m"
        limits:
          memory: "32Mi"
          cpu: "1"
      ports:
        - containerPort: 80
          protocol: TCP